name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          echo "PATH before update: $PATH"
          export PATH="$PATH:$HOME/.railway/bin"
          echo "PATH after update: $PATH"
          railway --version

      - name: Debug environment
        run: env

      - name: Link Railway Project
        run: |
          railway login --token ${{ secrets.RAILWAY_API_KEY }}
          railway link
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
